import UIKit

public class PersonLayer {
    public static func create(filledWith fillColor: UIColor) -> CAShapeLayer {

        let rootLayer = CAShapeLayer() // Generated by Svgsus

        let path = UIBezierPath()
        path.move(to: CGPoint(x: 0.962, y: 109.018))
        path.addLine(to: CGPoint(x: 0.962, y: 50.089))
        path.addCurve(to: CGPoint(x: 10.575, y: 40.268), controlPoint1: CGPoint(x: 0.962, y: 44.688), controlPoint2: CGPoint(x: 5.287999999999999, y: 40.268))
        path.addLine(to: CGPoint(x: 12.981, y: 40.268))
        path.addCurve(to: CGPoint(x: 3.846, y: 22.589000000000002), controlPoint1: CGPoint(x: 7.692, y: 36.339), controlPoint2: CGPoint(x: 3.846, y: 29.955))
        path.addCurve(to: CGPoint(x: 25, y: 0.982), controlPoint1: CGPoint(x: 3.846, y: 10.804), controlPoint2: CGPoint(x: 13.462, y: 0.982))
        path.addCurve(to: CGPoint(x: 46.153999999999996, y: 22.589), controlPoint1: CGPoint(x: 36.538, y: 0.982), controlPoint2: CGPoint(x: 46.153999999999996, y: 10.803999999999998))
        path.addCurve(to: CGPoint(x: 37.019, y: 40.268), controlPoint1: CGPoint(x: 46.153999999999996, y: 29.955), controlPoint2: CGPoint(x: 42.30799999999999, y: 36.339))
        path.addLine(to: CGPoint(x: 39.425, y: 40.268))
        path.addCurve(to: CGPoint(x: 49.038, y: 50.089), controlPoint1: CGPoint(x: 44.711999999999996, y: 40.268), controlPoint2: CGPoint(x: 49.038, y: 44.688))
        path.addLine(to: CGPoint(x: 49.038, y: 109.018))
        path.addLine(to: CGPoint(x: 0.962, y: 109.018))
        path.close()
        rootLayer.path = path.cgPath

        rootLayer.fillColor = fillColor.cgColor
        rootLayer.strokeColor = UIColor.darkGray.cgColor
        rootLayer.lineWidth = 2

        return rootLayer
    }
}
